name: Basic Vertx App CI

on:
  push:
    branches: ["pi-t-2295-github-actions-builds"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "zulu"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: gradle build --warning-mode all

      - name: Publish to GitHub Packages
        run: gradle publish --warning-mode all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
