name: Pinnacl Commons CI

env:
  BRANCH_NAME: "pi-t-2295-github-actions-builds"
  JAVA_VERSION: "21"
  JAVA_DISTRIBUTION: "zulu"

on:
  push:
    branches: [$BRANCH_NAME]
  pull_request:
    branches: [$BRANCH_NAME]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "$JAVA_VERSION"
          distribution: "$JAVA_DISTRIBUTION"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

  # dependency-submission:

  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'

  #   - name: Generate and submit dependency graph
  #     uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
