# name: List Installed Packages

# on: [push]

# jobs:
#   list-packages:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repository
#         uses: actions/checkout@v2

#       - name: List installed packages
#         run: |
#           helm version
#           gradle -v
